# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global:
  - MAKEFLAGS="-j 2"

bioc_packages: Biobase

r_packages:
  - NMF
  - RANN
  - fastICA
  - RcppRoll
  - Matrix
  - ipred
  - RSpectra


r:
- 3.1
- 3.2
- oldrel
- release
# travis is using the wrong r-devel on 3/4/19 (3.6.0 instewad of 3.5.2)
# - devel

matrix:
  fast_finish: true
  allow_failures:
    - r: 3.1
    - r: 3.2

after_success:
  - Rscript -e 'covr::codecov()'
