# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global:
  - MAKEFLAGS="-j 2"

bioc_packages: Biobase

r_packages:
  - NMF
  - RANN
  - fastICA
  - RcppRoll
  - Matrix
  - ipred
  - RSpectra
  # For Articles
  - caret
  - yardstick

matrix:
  fast_finish: true
  include:
  - r: devel
    after_success:
      - find . -name testthat.Rout | xargs cat        
    after_failure:
      - find . -name testthat.Rout | xargs cat
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    - find . -name testthat.Rout | xargs cat
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("tidyverse/tidytemplate")'
    after_failure:
      - find . -name testthat.Rout | xargs cat
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
  - r: 3.2
  - r: oldrel  
  allow_failures:
  - r: 3.2
  - r: oldrel  

#  oldrel fails due to a caret dependency